services:
  grott:
    image: ledidobe/grott
    networks:
      - net
    restart: always
    ports:
      - "5279:5279"
    environment:
      - gmqttip=172.18.1.10
      - ginvtype=sph
      - ggrowattip=47.254.130.145

  mqtt:
    image: eclipse-mosquitto
    restart: always
    networks:
      net:
         ipv4_address: 172.18.1.10
    ports:
      - "37000:1883"
      - "37001:9001"
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log

  surreal:
    image: surrealdb/surrealdb
    command: start file:/data/store.db
    restart: always
    ports:
      - "37002:8000"
    volumes:
      - ./db:/data

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.18.1.0/24
